import { Link, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Navbar } from '../components/Navbar';
import { marketplaceApi } from '../api/marketplaceApi';

export function BookingDetailPage() {
  const id = Number(useParams<{ id: string }>().id);
  const { data, isLoading, isError } = useQuery({ queryKey: ['booking', id], queryFn: () => marketplaceApi.getBooking(id), enabled: Number.isInteger(id) && id > 0 });
  return <div className="min-h-screen bg-gray-50 text-gray-900 dark:bg-gray-950 dark:text-white"><Navbar /><main className="mx-auto max-w-3xl px-4 py-10">{isLoading ? <p className="text-gray-500">Loading booking...</p> : isError || !data ? <div className="text-center"><p className="text-rose-500">Booking not found.</p><Link to="/dashboard" className="mt-4 inline-block text-sky-600 hover:underline">Back to dashboard</Link></div> : <article className="rounded-3xl border border-gray-200 bg-white p-7 shadow-md dark:border-gray-800 dark:bg-gray-900"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold text-indigo-600 dark:text-sky-400">{data.categoryName}</p><h1 className="mt-1 text-2xl font-extrabold">Booking #{data.id}</h1></div><span className="h-fit rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{data.status}</span></div><div className="mt-7 grid gap-5 border-t border-gray-100 pt-6 text-sm dark:border-gray-800 sm:grid-cols-2"><div><p className="text-xs text-gray-500">Worker</p><p className="font-semibold">{data.workerName}</p></div><div><p className="text-xs text-gray-500">Customer</p><p className="font-semibold">{data.customerName}</p></div><div><p className="text-xs text-gray-500">Agreed price</p><p className="font-semibold text-emerald-600 dark:text-emerald-400">৳ {data.agreedPrice.toLocaleString()}</p></div><div><p className="text-xs text-gray-500">Scheduled for</p><p className="font-semibold">{new Date(data.scheduledDate).toLocaleString()}</p></div><div className="sm:col-span-2"><p className="text-xs text-gray-500">Address</p><p className="font-semibold">📍 {data.address}</p></div>{data.description && <div className="sm:col-span-2"><p className="text-xs text-gray-500">Job description</p><p className="whitespace-pre-wrap">{data.description}</p></div>}</div></article>}</main></div>;
}
